#spring.application.name=demo
spring:
  application:
    name: demo


  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect






  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update